2016-02-02 15:21:01.734 [error] <0.3957.0> gen_server <0.3957.0> terminated with reason: heartbeat_timeout
2016-02-02 15:21:01.735 [error] <0.3957.0> CRASH REPORT Process <0.3957.0> with 15 neighbours exited with reason: heartbeat_timeout in gen_server:terminate/7 line 826
2016-02-02 15:21:01.736 [error] <0.3954.0> Supervisor {<0.3954.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3955.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.3",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3957.0> exit with reason heartbeat_timeout in context child_terminated
2016-02-02 15:21:01.736 [error] <0.3954.0> Supervisor {<0.3954.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3955.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.3",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3957.0> exit with reason reached_max_restart_intensity in context shutdown
2016-02-02 15:21:01.736 [error] <0.3816.0> gen_server <0.3816.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3764.0>,heartbeat_timeout}, {state,#Port<0.9828>,<<"client 10.10.10.1:55747 -> 10.10.10.4:5672">>,20,<0.3956.0>,131072,<0.3815.0>,...}) line 60
2016-02-02 15:21:01.737 [error] <0.3816.0> CRASH REPORT Process <0.3816.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3764.0>,heartbeat_timeout}, {state,#Port<0.9828>,<<"client 10.10.10.1:55747 -> 10.10.10.4:5672">>,20,<0.3956.0>,131072,<0.3815.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.737 [error] <0.3840.0> gen_server <0.3840.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3763.0>,heartbeat_timeout}, {state,#Port<0.9841>,<<"client 10.10.10.1:57390 -> 10.10.10.3:5672">>,20,<0.4136.0>,131072,<0.3839.0>,...}) line 60
2016-02-02 15:21:01.737 [error] <0.3925.0> gen_server <0.3925.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3766.0>,heartbeat_timeout}, {state,#Port<0.9861>,<<"client 10.10.10.1:56552 -> 10.10.10.3:5672">>,20,<0.4110.0>,131072,<0.3924.0>,...}) line 60
2016-02-02 15:21:01.737 [error] <0.3840.0> CRASH REPORT Process <0.3840.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3763.0>,heartbeat_timeout}, {state,#Port<0.9841>,<<"client 10.10.10.1:57390 -> 10.10.10.3:5672">>,20,<0.4136.0>,131072,<0.3839.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.738 [error] <0.3843.0> gen_server <0.3843.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3767.0>,heartbeat_timeout}, {state,#Port<0.9840>,<<"client 10.10.10.1:34573 -> 10.10.10.3:5672">>,20,<0.4131.0>,131072,<0.3842.0>,...}) line 60
2016-02-02 15:21:01.738 [error] <0.3925.0> CRASH REPORT Process <0.3925.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3766.0>,heartbeat_timeout}, {state,#Port<0.9861>,<<"client 10.10.10.1:56552 -> 10.10.10.3:5672">>,20,<0.4110.0>,131072,<0.3924.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.739 [error] <0.3843.0> CRASH REPORT Process <0.3843.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3767.0>,heartbeat_timeout}, {state,#Port<0.9840>,<<"client 10.10.10.1:34573 -> 10.10.10.3:5672">>,20,<0.4131.0>,131072,<0.3842.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.739 [error] <0.3897.0> gen_server <0.3897.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3772.0>,heartbeat_timeout}, {state,#Port<0.9854>,<<"client 10.10.10.1:42832 -> 10.10.10.3:5672">>,20,<0.4150.0>,131072,<0.3896.0>,...}) line 60
2016-02-02 15:21:01.739 [error] <0.3923.0> Supervisor {<0.3923.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3924.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.3",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3925.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3766.0>,heartbeat_timeout}, {state,#Port<0.9861>,<<"client 10.10.10.1:56552 -> 10.10.10.3:5672">>,20,<0.4110.0>,131072,<0.3924.0>,...}) line 60 in context child_terminated
2016-02-02 15:21:01.739 [error] <0.3825.0> gen_server <0.3825.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3768.0>,heartbeat_timeout}, {state,#Port<0.9831>,<<"client 10.10.10.1:51285 -> 10.10.10.2:5672">>,20,<0.4064.0>,131072,<0.3824.0>,...}) line 60
2016-02-02 15:21:01.739 [error] <0.3923.0> Supervisor {<0.3923.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3924.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.3",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3925.0> exit with reason reached_max_restart_intensity in context shutdown
2016-02-02 15:21:01.739 [error] <0.3825.0> CRASH REPORT Process <0.3825.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3768.0>,heartbeat_timeout}, {state,#Port<0.9831>,<<"client 10.10.10.1:51285 -> 10.10.10.2:5672">>,20,<0.4064.0>,131072,<0.3824.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.739 [error] <0.3897.0> CRASH REPORT Process <0.3897.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3772.0>,heartbeat_timeout}, {state,#Port<0.9854>,<<"client 10.10.10.1:42832 -> 10.10.10.3:5672">>,20,<0.4150.0>,131072,<0.3896.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.740 [error] <0.3823.0> Supervisor {<0.3823.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3824.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.2",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3825.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3768.0>,heartbeat_timeout}, {state,#Port<0.9831>,<<"client 10.10.10.1:51285 -> 10.10.10.2:5672">>,20,<0.4064.0>,131072,<0.3824.0>,...}) line 60 in context child_terminated
2016-02-02 15:21:01.740 [error] <0.3823.0> Supervisor {<0.3823.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3824.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.2",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3825.0> exit with reason reached_max_restart_intensity in context shutdown
2016-02-02 15:21:01.740 [error] <0.3909.0> gen_server <0.3909.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3776.0>,heartbeat_timeout}, {state,#Port<0.9856>,<<"client 10.10.10.1:57808 -> 10.10.10.3:5672">>,20,<0.4142.0>,131072,<0.3908.0>,...}) line 60
2016-02-02 15:21:01.740 [error] <0.3819.0> gen_server <0.3819.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3765.0>,heartbeat_timeout}, {state,#Port<0.9826>,<<"client 10.10.10.1:54448 -> 10.10.10.3:5672">>,20,<0.4090.0>,131072,<0.3818.0>,...}) line 60
2016-02-02 15:21:01.740 [error] <0.3819.0> CRASH REPORT Process <0.3819.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3765.0>,heartbeat_timeout}, {state,#Port<0.9826>,<<"client 10.10.10.1:54448 -> 10.10.10.3:5672">>,20,<0.4090.0>,131072,<0.3818.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.740 [error] <0.3909.0> CRASH REPORT Process <0.3909.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3776.0>,heartbeat_timeout}, {state,#Port<0.9856>,<<"client 10.10.10.1:57808 -> 10.10.10.3:5672">>,20,<0.4142.0>,131072,<0.3908.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.741 [error] <0.3817.0> Supervisor {<0.3817.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3818.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.3",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3819.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3765.0>,heartbeat_timeout}, {state,#Port<0.9826>,<<"client 10.10.10.1:54448 -> 10.10.10.3:5672">>,20,<0.4090.0>,131072,<0.3818.0>,...}) line 60 in context child_terminated
2016-02-02 15:21:01.741 [error] <0.3817.0> Supervisor {<0.3817.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3818.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.3",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3819.0> exit with reason reached_max_restart_intensity in context shutdown
2016-02-02 15:21:01.741 [error] <0.3894.0> gen_server <0.3894.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3770.0>,heartbeat_timeout}, {state,#Port<0.9843>,<<"client 10.10.10.1:55605 -> 10.10.10.3:5672">>,20,<0.4111.0>,131072,<0.3893.0>,...}) line 60
2016-02-02 15:21:01.741 [error] <0.3891.0> gen_server <0.3891.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3769.0>,heartbeat_timeout}, {state,#Port<0.9836>,<<"client 10.10.10.1:33448 -> 10.10.10.3:5672">>,20,<0.4092.0>,131072,<0.3890.0>,...}) line 60
2016-02-02 15:21:01.741 [error] <0.3894.0> CRASH REPORT Process <0.3894.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3770.0>,heartbeat_timeout}, {state,#Port<0.9843>,<<"client 10.10.10.1:55605 -> 10.10.10.3:5672">>,20,<0.4111.0>,131072,<0.3893.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.741 [error] <0.3858.0> gen_server <0.3858.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3778.0>,heartbeat_timeout}, {state,#Port<0.9829>,<<"client 10.10.10.1:42989 -> 10.10.10.2:5672">>,20,<0.4039.0>,131072,<0.3857.0>,...}) line 60
2016-02-02 15:21:01.741 [error] <0.3891.0> CRASH REPORT Process <0.3891.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3769.0>,heartbeat_timeout}, {state,#Port<0.9836>,<<"client 10.10.10.1:33448 -> 10.10.10.3:5672">>,20,<0.4092.0>,131072,<0.3890.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.741 [error] <0.3858.0> CRASH REPORT Process <0.3858.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3778.0>,heartbeat_timeout}, {state,#Port<0.9829>,<<"client 10.10.10.1:42989 -> 10.10.10.2:5672">>,20,<0.4039.0>,131072,<0.3857.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.742 [error] <0.3856.0> Supervisor {<0.3856.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3857.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.2",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3858.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3778.0>,heartbeat_timeout}, {state,#Port<0.9829>,<<"client 10.10.10.1:42989 -> 10.10.10.2:5672">>,20,<0.4039.0>,131072,<0.3857.0>,...}) line 60 in context child_terminated
2016-02-02 15:21:01.742 [error] <0.3822.0> gen_server <0.3822.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3771.0>,heartbeat_timeout}, {state,#Port<0.9827>,<<"client 10.10.10.1:39903 -> 10.10.10.3:5672">>,20,<0.4078.0>,131072,<0.3821.0>,...}) line 60
2016-02-02 15:21:01.742 [error] <0.3856.0> Supervisor {<0.3856.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3857.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.2",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3858.0> exit with reason reached_max_restart_intensity in context shutdown
2016-02-02 15:21:01.742 [error] <0.3928.0> gen_server <0.3928.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3780.0>,heartbeat_timeout}, {state,#Port<0.9867>,<<"client 10.10.10.1:56472 -> 10.10.10.4:5672">>,20,<0.4016.0>,131072,<0.3927.0>,...}) line 60
2016-02-02 15:21:01.742 [error] <0.3822.0> CRASH REPORT Process <0.3822.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3771.0>,heartbeat_timeout}, {state,#Port<0.9827>,<<"client 10.10.10.1:39903 -> 10.10.10.3:5672">>,20,<0.4078.0>,131072,<0.3821.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.742 [error] <0.3928.0> CRASH REPORT Process <0.3928.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3780.0>,heartbeat_timeout}, {state,#Port<0.9867>,<<"client 10.10.10.1:56472 -> 10.10.10.4:5672">>,20,<0.4016.0>,131072,<0.3927.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.742 [error] <0.3831.0> gen_server <0.3831.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3774.0>,heartbeat_timeout}, {state,#Port<0.9842>,<<"client 10.10.10.1:59964 -> 10.10.10.4:5672">>,20,<0.3973.0>,131072,<0.3830.0>,...}) line 60
2016-02-02 15:21:01.742 [error] <0.3820.0> Supervisor {<0.3820.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3821.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.3",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3822.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3771.0>,heartbeat_timeout}, {state,#Port<0.9827>,<<"client 10.10.10.1:39903 -> 10.10.10.3:5672">>,20,<0.4078.0>,131072,<0.3821.0>,...}) line 60 in context child_terminated
2016-02-02 15:21:01.742 [error] <0.3820.0> Supervisor {<0.3820.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3821.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.3",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3822.0> exit with reason reached_max_restart_intensity in context shutdown
2016-02-02 15:21:01.743 [error] <0.3831.0> CRASH REPORT Process <0.3831.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3774.0>,heartbeat_timeout}, {state,#Port<0.9842>,<<"client 10.10.10.1:59964 -> 10.10.10.4:5672">>,20,<0.3973.0>,131072,<0.3830.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.743 [error] <0.3926.0> Supervisor {<0.3926.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3927.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.4",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3928.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3780.0>,heartbeat_timeout}, {state,#Port<0.9867>,<<"client 10.10.10.1:56472 -> 10.10.10.4:5672">>,20,<0.4016.0>,131072,<0.3927.0>,...}) line 60 in context child_terminated
2016-02-02 15:21:01.743 [error] <0.3926.0> Supervisor {<0.3926.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3927.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.4",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3928.0> exit with reason reached_max_restart_intensity in context shutdown
2016-02-02 15:21:01.743 [error] <0.3834.0> gen_server <0.3834.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3775.0>,heartbeat_timeout}, {state,#Port<0.9848>,<<"client 10.10.10.1:42611 -> 10.10.10.2:5672">>,20,<0.4052.0>,131072,<0.3833.0>,...}) line 60
2016-02-02 15:21:01.743 [error] <0.3885.0> gen_server <0.3885.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3786.0>,heartbeat_timeout}, {state,#Port<0.9847>,<<"client 10.10.10.1:41430 -> 10.10.10.4:5672">>,20,<0.3989.0>,131072,<0.3884.0>,...}) line 60
2016-02-02 15:21:01.743 [error] <0.3834.0> CRASH REPORT Process <0.3834.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3775.0>,heartbeat_timeout}, {state,#Port<0.9848>,<<"client 10.10.10.1:42611 -> 10.10.10.2:5672">>,20,<0.4052.0>,131072,<0.3833.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.743 [error] <0.3885.0> CRASH REPORT Process <0.3885.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3786.0>,heartbeat_timeout}, {state,#Port<0.9847>,<<"client 10.10.10.1:41430 -> 10.10.10.4:5672">>,20,<0.3989.0>,131072,<0.3884.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.743 [error] <0.3832.0> Supervisor {<0.3832.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3833.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.2",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3834.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3775.0>,heartbeat_timeout}, {state,#Port<0.9848>,<<"client 10.10.10.1:42611 -> 10.10.10.2:5672">>,20,<0.4052.0>,131072,<0.3833.0>,...}) line 60 in context child_terminated
2016-02-02 15:21:01.743 [error] <0.3832.0> Supervisor {<0.3832.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3833.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.2",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3834.0> exit with reason reached_max_restart_intensity in context shutdown
2016-02-02 15:21:01.743 [error] <0.3828.0> gen_server <0.3828.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3773.0>,heartbeat_timeout}, {state,#Port<0.9830>,<<"client 10.10.10.1:38651 -> 10.10.10.2:5672">>,20,<0.4072.0>,131072,<0.3827.0>,...}) line 60
2016-02-02 15:21:01.743 [error] <0.3883.0> Supervisor {<0.3883.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3884.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.4",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3885.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3786.0>,heartbeat_timeout}, {state,#Port<0.9847>,<<"client 10.10.10.1:41430 -> 10.10.10.4:5672">>,20,<0.3989.0>,131072,<0.3884.0>,...}) line 60 in context child_terminated
2016-02-02 15:21:01.744 [error] <0.3900.0> gen_server <0.3900.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3787.0>,heartbeat_timeout}, {state,#Port<0.9855>,<<"client 10.10.10.1:40576 -> 10.10.10.3:5672">>,20,<0.4161.0>,131072,<0.3899.0>,...}) line 60
2016-02-02 15:21:01.744 [error] <0.3883.0> Supervisor {<0.3883.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3884.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.4",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3885.0> exit with reason reached_max_restart_intensity in context shutdown
2016-02-02 15:21:01.744 [error] <0.3828.0> CRASH REPORT Process <0.3828.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3773.0>,heartbeat_timeout}, {state,#Port<0.9830>,<<"client 10.10.10.1:38651 -> 10.10.10.2:5672">>,20,<0.4072.0>,131072,<0.3827.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.744 [error] <0.3900.0> CRASH REPORT Process <0.3900.0> with 0 neighbours exited with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3787.0>,heartbeat_timeout}, {state,#Port<0.9855>,<<"client 10.10.10.1:40576 -> 10.10.10.3:5672">>,20,<0.4161.0>,131072,<0.3899.0>,...}) line 60 in gen_server:terminate/7 line 826
2016-02-02 15:21:01.744 [error] <0.3826.0> Supervisor {<0.3826.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3827.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"10.10.10.2",5672,0,0,20,infinity,none,[#Fun<a..>,...],...}) at <0.3828.0> exit with reason no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3773.0>,heartbeat_timeout}, {state,#Port<0.9830>,<<"client 10.10.10.1:38651 -> 10.10.10.2:5672">>,20,<0.4072.0>,131072,<0.3827.0>,...}) line 60 in context child_terminated
2016-02-02 15:21:01.744 [error] <0.3852.0> gen_server <0.3852.0> terminated with reason: no function clause matching amqp_network_connection:handle_message({'EXIT',<0.3791.0>,heartbeat_timeout}, {state,#Port<0.9839>,<<"client 10.10.10.1:49439 -> 10.10.10.2:5672">>,20,<0.4053.0>,131072,<0.3851.0>,...}) line 60
